// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignerApiClient is the client API for SignerApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignerApiClient interface {
	SignData(ctx context.Context, in *SignDataRequest, opts ...grpc.CallOption) (*SignDataResponse, error)
}

type signerApiClient struct {
	cc grpc.ClientConnInterface
}

func NewSignerApiClient(cc grpc.ClientConnInterface) SignerApiClient {
	return &signerApiClient{cc}
}

func (c *signerApiClient) SignData(ctx context.Context, in *SignDataRequest, opts ...grpc.CallOption) (*SignDataResponse, error) {
	out := new(SignDataResponse)
	err := c.cc.Invoke(ctx, "/signer.SignerApi/SignData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignerApiServer is the server API for SignerApi service.
// All implementations must embed UnimplementedSignerApiServer
// for forward compatibility
type SignerApiServer interface {
	SignData(context.Context, *SignDataRequest) (*SignDataResponse, error)
	mustEmbedUnimplementedSignerApiServer()
}

// UnimplementedSignerApiServer must be embedded to have forward compatible implementations.
type UnimplementedSignerApiServer struct {
}

func (UnimplementedSignerApiServer) SignData(context.Context, *SignDataRequest) (*SignDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignData not implemented")
}
func (UnimplementedSignerApiServer) mustEmbedUnimplementedSignerApiServer() {}

// UnsafeSignerApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignerApiServer will
// result in compilation errors.
type UnsafeSignerApiServer interface {
	mustEmbedUnimplementedSignerApiServer()
}

func RegisterSignerApiServer(s grpc.ServiceRegistrar, srv SignerApiServer) {
	s.RegisterService(&SignerApi_ServiceDesc, srv)
}

func _SignerApi_SignData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerApiServer).SignData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signer.SignerApi/SignData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerApiServer).SignData(ctx, req.(*SignDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignerApi_ServiceDesc is the grpc.ServiceDesc for SignerApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignerApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signer.SignerApi",
	HandlerType: (*SignerApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignData",
			Handler:    _SignerApi_SignData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
