syntax = "proto3";

package pb;

option go_package = "ticktaktoe/pb";

enum ErrorReasons {
  MATCH_ALREADY_EXISTS = 0;
}

enum MatchProgressStatus {
  MATCH_STILL_IN_PROGRESS = 0;
  MATCH_ALREADY_ENDED = 1;
}

enum CurrentMovementStatus {
  AWAIT_FOR_0_MOVE = 0;
  AWAIT_FOR_X_MOVE = 1;
}

enum NextMovementStatus {
  NEXT_MOVE_O = 0;
  NEXT_MOVE_X = 1;
}

message MatchStatus {
  MatchProgressStatus ProgressStatus = 1;
  CurrentMovementStatus MovementStatus = 2;
  NextMovementStatus NextMove = 3;
}

message MatchInfo {
  string MatchUUID = 1;
  MatchStatus MatchStatus = 2;
}

message JoinToLobbyRequest {
  string UserUUID = 1;
}

message JoinToLobbyResponse {
  string UserUUID = 1;
  string TokenUUID = 2;
}

message StartMatchRequest {
  uint32 BattleFieldSize = 1;
}

message StartMatchResponse {
  string MatchUUID = 1;
  uint32 BattleFieldSize = 2;
  MatchStatus MatchStatus = 3;
}

message PlayerMoveRequest {
  string MatchUUID = 1;
}

message PlayerMoveResponse {
  string MatchUUID = 1;
  MatchStatus MatchStatus = 2;
}

message MatchStatusRequest {
  string MatchUUID = 1;
}

message MatchStatusResponse {
  string MatchUUID = 1;
  MatchStatus MatchStatus = 2;
}

message StopMatchRequest {
  string GameUUID = 1;
}

message StopMatchResponse {
  string GameUUID = 1;
  MatchStatus MatchStatus = 2;
}

message MathListRequest {
}

message MathListResponse {
  repeated MatchInfo MatchList = 1;
}

service GameApi {
  rpc JoinToLobby                 (JoinToLobbyRequest)               returns (JoinToLobbyResponse) {}
  rpc StartMatch                    (StartMatchRequest)                returns (StartMatchResponse) {}
  rpc StopMatch                     (StartMatchRequest)                returns (StartMatchResponse) {}
  rpc PlayerMove                      (PlayerMoveRequest)                  returns (PlayerMoveResponse) {}
  rpc GetMathStatus                    (MatchStatusRequest)               returns (MatchStatusResponse) {}
  rpc GetMathList                      (MathListRequest)                  returns (MathListResponse) {}
}