// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameApiClient is the client API for GameApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameApiClient interface {
	JoinToLobby(ctx context.Context, in *JoinToLobbyRequest, opts ...grpc.CallOption) (*JoinToLobbyResponse, error)
	StopMatch(ctx context.Context, in *StopMatchRequest, opts ...grpc.CallOption) (*StopMatchResponse, error)
	PlayerMove(ctx context.Context, in *PlayerMoveRequest, opts ...grpc.CallOption) (*PlayerMoveResponse, error)
	GetMatchStatus(ctx context.Context, in *MatchStatusRequest, opts ...grpc.CallOption) (*MatchStatusResponse, error)
	GetMatchMovementList(ctx context.Context, in *MatchMovementListRequest, opts ...grpc.CallOption) (*MatchMovementListResponse, error)
	GetMatchList(ctx context.Context, in *MathListRequest, opts ...grpc.CallOption) (*MathListResponse, error)
}

type gameApiClient struct {
	cc grpc.ClientConnInterface
}

func NewGameApiClient(cc grpc.ClientConnInterface) GameApiClient {
	return &gameApiClient{cc}
}

func (c *gameApiClient) JoinToLobby(ctx context.Context, in *JoinToLobbyRequest, opts ...grpc.CallOption) (*JoinToLobbyResponse, error) {
	out := new(JoinToLobbyResponse)
	err := c.cc.Invoke(ctx, "/pb.GameApi/JoinToLobby", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) StopMatch(ctx context.Context, in *StopMatchRequest, opts ...grpc.CallOption) (*StopMatchResponse, error) {
	out := new(StopMatchResponse)
	err := c.cc.Invoke(ctx, "/pb.GameApi/StopMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) PlayerMove(ctx context.Context, in *PlayerMoveRequest, opts ...grpc.CallOption) (*PlayerMoveResponse, error) {
	out := new(PlayerMoveResponse)
	err := c.cc.Invoke(ctx, "/pb.GameApi/PlayerMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) GetMatchStatus(ctx context.Context, in *MatchStatusRequest, opts ...grpc.CallOption) (*MatchStatusResponse, error) {
	out := new(MatchStatusResponse)
	err := c.cc.Invoke(ctx, "/pb.GameApi/GetMatchStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) GetMatchMovementList(ctx context.Context, in *MatchMovementListRequest, opts ...grpc.CallOption) (*MatchMovementListResponse, error) {
	out := new(MatchMovementListResponse)
	err := c.cc.Invoke(ctx, "/pb.GameApi/GetMatchMovementList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameApiClient) GetMatchList(ctx context.Context, in *MathListRequest, opts ...grpc.CallOption) (*MathListResponse, error) {
	out := new(MathListResponse)
	err := c.cc.Invoke(ctx, "/pb.GameApi/GetMatchList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameApiServer is the server API for GameApi service.
// All implementations must embed UnimplementedGameApiServer
// for forward compatibility
type GameApiServer interface {
	JoinToLobby(context.Context, *JoinToLobbyRequest) (*JoinToLobbyResponse, error)
	StopMatch(context.Context, *StopMatchRequest) (*StopMatchResponse, error)
	PlayerMove(context.Context, *PlayerMoveRequest) (*PlayerMoveResponse, error)
	GetMatchStatus(context.Context, *MatchStatusRequest) (*MatchStatusResponse, error)
	GetMatchMovementList(context.Context, *MatchMovementListRequest) (*MatchMovementListResponse, error)
	GetMatchList(context.Context, *MathListRequest) (*MathListResponse, error)
	mustEmbedUnimplementedGameApiServer()
}

// UnimplementedGameApiServer must be embedded to have forward compatible implementations.
type UnimplementedGameApiServer struct {
}

func (UnimplementedGameApiServer) JoinToLobby(context.Context, *JoinToLobbyRequest) (*JoinToLobbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinToLobby not implemented")
}
func (UnimplementedGameApiServer) StopMatch(context.Context, *StopMatchRequest) (*StopMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopMatch not implemented")
}
func (UnimplementedGameApiServer) PlayerMove(context.Context, *PlayerMoveRequest) (*PlayerMoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerMove not implemented")
}
func (UnimplementedGameApiServer) GetMatchStatus(context.Context, *MatchStatusRequest) (*MatchStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchStatus not implemented")
}
func (UnimplementedGameApiServer) GetMatchMovementList(context.Context, *MatchMovementListRequest) (*MatchMovementListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchMovementList not implemented")
}
func (UnimplementedGameApiServer) GetMatchList(context.Context, *MathListRequest) (*MathListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchList not implemented")
}
func (UnimplementedGameApiServer) mustEmbedUnimplementedGameApiServer() {}

// UnsafeGameApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameApiServer will
// result in compilation errors.
type UnsafeGameApiServer interface {
	mustEmbedUnimplementedGameApiServer()
}

func RegisterGameApiServer(s grpc.ServiceRegistrar, srv GameApiServer) {
	s.RegisterService(&GameApi_ServiceDesc, srv)
}

func _GameApi_JoinToLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinToLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).JoinToLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameApi/JoinToLobby",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).JoinToLobby(ctx, req.(*JoinToLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_StopMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).StopMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameApi/StopMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).StopMatch(ctx, req.(*StopMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_PlayerMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).PlayerMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameApi/PlayerMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).PlayerMove(ctx, req.(*PlayerMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_GetMatchStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).GetMatchStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameApi/GetMatchStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).GetMatchStatus(ctx, req.(*MatchStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_GetMatchMovementList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchMovementListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).GetMatchMovementList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameApi/GetMatchMovementList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).GetMatchMovementList(ctx, req.(*MatchMovementListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameApi_GetMatchList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MathListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameApiServer).GetMatchList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameApi/GetMatchList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameApiServer).GetMatchList(ctx, req.(*MathListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameApi_ServiceDesc is the grpc.ServiceDesc for GameApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GameApi",
	HandlerType: (*GameApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinToLobby",
			Handler:    _GameApi_JoinToLobby_Handler,
		},
		{
			MethodName: "StopMatch",
			Handler:    _GameApi_StopMatch_Handler,
		},
		{
			MethodName: "PlayerMove",
			Handler:    _GameApi_PlayerMove_Handler,
		},
		{
			MethodName: "GetMatchStatus",
			Handler:    _GameApi_GetMatchStatus_Handler,
		},
		{
			MethodName: "GetMatchMovementList",
			Handler:    _GameApi_GetMatchMovementList_Handler,
		},
		{
			MethodName: "GetMatchList",
			Handler:    _GameApi_GetMatchList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
