// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.27.3
// source: server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReasons int32

const (
	ErrorReasons_MATCH_ALREADY_EXISTS ErrorReasons = 0
)

// Enum value maps for ErrorReasons.
var (
	ErrorReasons_name = map[int32]string{
		0: "MATCH_ALREADY_EXISTS",
	}
	ErrorReasons_value = map[string]int32{
		"MATCH_ALREADY_EXISTS": 0,
	}
)

func (x ErrorReasons) Enum() *ErrorReasons {
	p := new(ErrorReasons)
	*p = x
	return p
}

func (x ErrorReasons) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReasons) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (ErrorReasons) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x ErrorReasons) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReasons.Descriptor instead.
func (ErrorReasons) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type MatchProgressStatus int32

const (
	MatchProgressStatus_MATCH_STATUS_PLACEHOLDER MatchProgressStatus = 0
	MatchProgressStatus_MATCH_STILL_IN_PROGRESS  MatchProgressStatus = 1
	MatchProgressStatus_MATCH_ALREADY_ENDED      MatchProgressStatus = 2
)

// Enum value maps for MatchProgressStatus.
var (
	MatchProgressStatus_name = map[int32]string{
		0: "MATCH_STATUS_PLACEHOLDER",
		1: "MATCH_STILL_IN_PROGRESS",
		2: "MATCH_ALREADY_ENDED",
	}
	MatchProgressStatus_value = map[string]int32{
		"MATCH_STATUS_PLACEHOLDER": 0,
		"MATCH_STILL_IN_PROGRESS":  1,
		"MATCH_ALREADY_ENDED":      2,
	}
)

func (x MatchProgressStatus) Enum() *MatchProgressStatus {
	p := new(MatchProgressStatus)
	*p = x
	return p
}

func (x MatchProgressStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchProgressStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[1].Descriptor()
}

func (MatchProgressStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[1]
}

func (x MatchProgressStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchProgressStatus.Descriptor instead.
func (MatchProgressStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

type MovementStatus int32

const (
	MovementStatus_MOVE_OF_PLACEHOLDER MovementStatus = 0
	MovementStatus_MOVE_OF_X           MovementStatus = 1
	MovementStatus_MOVE_OF_O           MovementStatus = 2
)

// Enum value maps for MovementStatus.
var (
	MovementStatus_name = map[int32]string{
		0: "MOVE_OF_PLACEHOLDER",
		1: "MOVE_OF_X",
		2: "MOVE_OF_O",
	}
	MovementStatus_value = map[string]int32{
		"MOVE_OF_PLACEHOLDER": 0,
		"MOVE_OF_X":           1,
		"MOVE_OF_O":           2,
	}
)

func (x MovementStatus) Enum() *MovementStatus {
	p := new(MovementStatus)
	*p = x
	return p
}

func (x MovementStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovementStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[2].Descriptor()
}

func (MovementStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[2]
}

func (x MovementStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovementStatus.Descriptor instead.
func (MovementStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

type MovementInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerUUID string `protobuf:"bytes,1,opt,name=PlayerUUID,proto3" json:"PlayerUUID,omitempty"`
	PositionX  uint32 `protobuf:"varint,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY  uint32 `protobuf:"varint,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
}

func (x *MovementInfo) Reset() {
	*x = MovementInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementInfo) ProtoMessage() {}

func (x *MovementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementInfo.ProtoReflect.Descriptor instead.
func (*MovementInfo) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *MovementInfo) GetPlayerUUID() string {
	if x != nil {
		return x.PlayerUUID
	}
	return ""
}

func (x *MovementInfo) GetPositionX() uint32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *MovementInfo) GetPositionY() uint32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

type MatchStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProgressStatus        MatchProgressStatus `protobuf:"varint,1,opt,name=ProgressStatus,proto3,enum=pb.MatchProgressStatus" json:"ProgressStatus,omitempty"`
	CurrentMovementStatus MovementStatus      `protobuf:"varint,2,opt,name=CurrentMovementStatus,proto3,enum=pb.MovementStatus" json:"CurrentMovementStatus,omitempty"`
	NextMoveStatus        MovementStatus      `protobuf:"varint,3,opt,name=NextMoveStatus,proto3,enum=pb.MovementStatus" json:"NextMoveStatus,omitempty"`
}

func (x *MatchStatus) Reset() {
	*x = MatchStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatus) ProtoMessage() {}

func (x *MatchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatus.ProtoReflect.Descriptor instead.
func (*MatchStatus) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *MatchStatus) GetProgressStatus() MatchProgressStatus {
	if x != nil {
		return x.ProgressStatus
	}
	return MatchProgressStatus_MATCH_STATUS_PLACEHOLDER
}

func (x *MatchStatus) GetCurrentMovementStatus() MovementStatus {
	if x != nil {
		return x.CurrentMovementStatus
	}
	return MovementStatus_MOVE_OF_PLACEHOLDER
}

func (x *MatchStatus) GetNextMoveStatus() MovementStatus {
	if x != nil {
		return x.NextMoveStatus
	}
	return MovementStatus_MOVE_OF_PLACEHOLDER
}

type MatchInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID   string       `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
	MatchStatus *MatchStatus `protobuf:"bytes,2,opt,name=MatchStatus,proto3" json:"MatchStatus,omitempty"`
}

func (x *MatchInfo) Reset() {
	*x = MatchInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfo) ProtoMessage() {}

func (x *MatchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfo.ProtoReflect.Descriptor instead.
func (*MatchInfo) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *MatchInfo) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

func (x *MatchInfo) GetMatchStatus() *MatchStatus {
	if x != nil {
		return x.MatchStatus
	}
	return nil
}

type JoinToLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUUID string `protobuf:"bytes,1,opt,name=UserUUID,proto3" json:"UserUUID,omitempty"`
}

func (x *JoinToLobbyRequest) Reset() {
	*x = JoinToLobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinToLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToLobbyRequest) ProtoMessage() {}

func (x *JoinToLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToLobbyRequest.ProtoReflect.Descriptor instead.
func (*JoinToLobbyRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *JoinToLobbyRequest) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

type JoinToLobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUUID  string `protobuf:"bytes,1,opt,name=UserUUID,proto3" json:"UserUUID,omitempty"`
	TokenUUID string `protobuf:"bytes,2,opt,name=TokenUUID,proto3" json:"TokenUUID,omitempty"`
}

func (x *JoinToLobbyResponse) Reset() {
	*x = JoinToLobbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinToLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToLobbyResponse) ProtoMessage() {}

func (x *JoinToLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToLobbyResponse.ProtoReflect.Descriptor instead.
func (*JoinToLobbyResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *JoinToLobbyResponse) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

func (x *JoinToLobbyResponse) GetTokenUUID() string {
	if x != nil {
		return x.TokenUUID
	}
	return ""
}

type PlayerMoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID  string `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
	PlayerUUID string `protobuf:"bytes,2,opt,name=PlayerUUID,proto3" json:"PlayerUUID,omitempty"`
	PositionX  uint32 `protobuf:"varint,3,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY  uint32 `protobuf:"varint,4,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
}

func (x *PlayerMoveRequest) Reset() {
	*x = PlayerMoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMoveRequest) ProtoMessage() {}

func (x *PlayerMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMoveRequest.ProtoReflect.Descriptor instead.
func (*PlayerMoveRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerMoveRequest) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

func (x *PlayerMoveRequest) GetPlayerUUID() string {
	if x != nil {
		return x.PlayerUUID
	}
	return ""
}

func (x *PlayerMoveRequest) GetPositionX() uint32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *PlayerMoveRequest) GetPositionY() uint32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

type PlayerMoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID   string       `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
	PlayerUUID  string       `protobuf:"bytes,2,opt,name=PlayerUUID,proto3" json:"PlayerUUID,omitempty"`
	MatchStatus *MatchStatus `protobuf:"bytes,3,opt,name=MatchStatus,proto3" json:"MatchStatus,omitempty"`
	PositionX   uint32       `protobuf:"varint,4,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY   uint32       `protobuf:"varint,5,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
}

func (x *PlayerMoveResponse) Reset() {
	*x = PlayerMoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMoveResponse) ProtoMessage() {}

func (x *PlayerMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMoveResponse.ProtoReflect.Descriptor instead.
func (*PlayerMoveResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerMoveResponse) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

func (x *PlayerMoveResponse) GetPlayerUUID() string {
	if x != nil {
		return x.PlayerUUID
	}
	return ""
}

func (x *PlayerMoveResponse) GetMatchStatus() *MatchStatus {
	if x != nil {
		return x.MatchStatus
	}
	return nil
}

func (x *PlayerMoveResponse) GetPositionX() uint32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *PlayerMoveResponse) GetPositionY() uint32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

type MatchStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID string `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
}

func (x *MatchStatusRequest) Reset() {
	*x = MatchStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatusRequest) ProtoMessage() {}

func (x *MatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatusRequest.ProtoReflect.Descriptor instead.
func (*MatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *MatchStatusRequest) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

type MatchStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID   string       `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
	MatchStatus *MatchStatus `protobuf:"bytes,2,opt,name=MatchStatus,proto3" json:"MatchStatus,omitempty"`
}

func (x *MatchStatusResponse) Reset() {
	*x = MatchStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatusResponse) ProtoMessage() {}

func (x *MatchStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatusResponse.ProtoReflect.Descriptor instead.
func (*MatchStatusResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *MatchStatusResponse) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

func (x *MatchStatusResponse) GetMatchStatus() *MatchStatus {
	if x != nil {
		return x.MatchStatus
	}
	return nil
}

type StopMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID string `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
}

func (x *StopMatchRequest) Reset() {
	*x = StopMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMatchRequest) ProtoMessage() {}

func (x *StopMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMatchRequest.ProtoReflect.Descriptor instead.
func (*StopMatchRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *StopMatchRequest) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

type StopMatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID   string       `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
	MatchStatus *MatchStatus `protobuf:"bytes,2,opt,name=MatchStatus,proto3" json:"MatchStatus,omitempty"`
}

func (x *StopMatchResponse) Reset() {
	*x = StopMatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMatchResponse) ProtoMessage() {}

func (x *StopMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMatchResponse.ProtoReflect.Descriptor instead.
func (*StopMatchResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *StopMatchResponse) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

func (x *StopMatchResponse) GetMatchStatus() *MatchStatus {
	if x != nil {
		return x.MatchStatus
	}
	return nil
}

type MathListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MathListRequest) Reset() {
	*x = MathListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MathListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathListRequest) ProtoMessage() {}

func (x *MathListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathListRequest.ProtoReflect.Descriptor instead.
func (*MathListRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

type MathListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchList []*MatchInfo `protobuf:"bytes,1,rep,name=MatchList,proto3" json:"MatchList,omitempty"`
}

func (x *MathListResponse) Reset() {
	*x = MathListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MathListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathListResponse) ProtoMessage() {}

func (x *MathListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathListResponse.ProtoReflect.Descriptor instead.
func (*MathListResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *MathListResponse) GetMatchList() []*MatchInfo {
	if x != nil {
		return x.MatchList
	}
	return nil
}

type MatchMovementListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID string `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
}

func (x *MatchMovementListRequest) Reset() {
	*x = MatchMovementListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchMovementListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMovementListRequest) ProtoMessage() {}

func (x *MatchMovementListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMovementListRequest.ProtoReflect.Descriptor instead.
func (*MatchMovementListRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *MatchMovementListRequest) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

type MatchMovementListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchInfo    *MatchInfo      `protobuf:"bytes,1,opt,name=MatchInfo,proto3" json:"MatchInfo,omitempty"`
	MovementList []*MovementInfo `protobuf:"bytes,2,rep,name=MovementList,proto3" json:"MovementList,omitempty"`
}

func (x *MatchMovementListResponse) Reset() {
	*x = MatchMovementListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchMovementListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMovementListResponse) ProtoMessage() {}

func (x *MatchMovementListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMovementListResponse.ProtoReflect.Descriptor instead.
func (*MatchMovementListResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{14}
}

func (x *MatchMovementListResponse) GetMatchInfo() *MatchInfo {
	if x != nil {
		return x.MatchInfo
	}
	return nil
}

func (x *MatchMovementListResponse) GetMovementList() []*MovementInfo {
	if x != nil {
		return x.MovementList
	}
	return nil
}

var File_server_proto protoreflect.FileDescriptor

var file_server_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x6a, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x55,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58,
	0x12, 0x1c, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x22, 0xd4,
	0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3f,
	0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x48, 0x0a, 0x15, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x15, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a, 0x0e, 0x4e, 0x65, 0x78,
	0x74, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44,
	0x12, 0x31, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x30, 0x0a, 0x12, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x4c, 0x6f, 0x62,
	0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x55, 0x49, 0x44, 0x22, 0x4f, 0x0a, 0x13, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x4c,
	0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x55, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x55, 0x55, 0x49, 0x44, 0x22, 0x8d, 0x01, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x22, 0xc1, 0x01, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x12, 0x31, 0x0a, 0x0b, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1c, 0x0a, 0x09,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x22, 0x32, 0x0a, 0x12, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x22, 0x66,
	0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55,
	0x55, 0x49, 0x44, 0x12, 0x31, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x30, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x22, 0x64, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x70,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x12, 0x31, 0x0a, 0x0b, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x11,
	0x0a, 0x0f, 0x4d, 0x61, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3f, 0x0a, 0x10, 0x4d, 0x61, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x38, 0x0a, 0x18, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x22, 0x7e, 0x0a, 0x19,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c,
	0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x28, 0x0a, 0x0c,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x14,
	0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58,
	0x49, 0x53, 0x54, 0x53, 0x10, 0x00, 0x2a, 0x69, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a,
	0x18, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x4c,
	0x41, 0x43, 0x45, 0x48, 0x4f, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x4d,
	0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x49, 0x4c, 0x4c, 0x5f, 0x49, 0x4e, 0x5f, 0x50, 0x52,
	0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x41, 0x54, 0x43,
	0x48, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10,
	0x02, 0x2a, 0x47, 0x0a, 0x0e, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4f, 0x46, 0x5f, 0x50,
	0x4c, 0x41, 0x43, 0x45, 0x48, 0x4f, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4f, 0x46, 0x5f, 0x58, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4d,
	0x4f, 0x56, 0x45, 0x5f, 0x4f, 0x46, 0x5f, 0x4f, 0x10, 0x02, 0x32, 0x9f, 0x03, 0x0a, 0x07, 0x47,
	0x61, 0x6d, 0x65, 0x41, 0x70, 0x69, 0x12, 0x40, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x54,
	0x6f, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x70,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x6f, 0x70, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f,
	0x76, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d,
	0x74, 0x69, 0x63, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData = file_server_proto_rawDesc
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_rawDescData)
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_server_proto_goTypes = []interface{}{
	(ErrorReasons)(0),                 // 0: pb.ErrorReasons
	(MatchProgressStatus)(0),          // 1: pb.MatchProgressStatus
	(MovementStatus)(0),               // 2: pb.MovementStatus
	(*MovementInfo)(nil),              // 3: pb.MovementInfo
	(*MatchStatus)(nil),               // 4: pb.MatchStatus
	(*MatchInfo)(nil),                 // 5: pb.MatchInfo
	(*JoinToLobbyRequest)(nil),        // 6: pb.JoinToLobbyRequest
	(*JoinToLobbyResponse)(nil),       // 7: pb.JoinToLobbyResponse
	(*PlayerMoveRequest)(nil),         // 8: pb.PlayerMoveRequest
	(*PlayerMoveResponse)(nil),        // 9: pb.PlayerMoveResponse
	(*MatchStatusRequest)(nil),        // 10: pb.MatchStatusRequest
	(*MatchStatusResponse)(nil),       // 11: pb.MatchStatusResponse
	(*StopMatchRequest)(nil),          // 12: pb.StopMatchRequest
	(*StopMatchResponse)(nil),         // 13: pb.StopMatchResponse
	(*MathListRequest)(nil),           // 14: pb.MathListRequest
	(*MathListResponse)(nil),          // 15: pb.MathListResponse
	(*MatchMovementListRequest)(nil),  // 16: pb.MatchMovementListRequest
	(*MatchMovementListResponse)(nil), // 17: pb.MatchMovementListResponse
}
var file_server_proto_depIdxs = []int32{
	1,  // 0: pb.MatchStatus.ProgressStatus:type_name -> pb.MatchProgressStatus
	2,  // 1: pb.MatchStatus.CurrentMovementStatus:type_name -> pb.MovementStatus
	2,  // 2: pb.MatchStatus.NextMoveStatus:type_name -> pb.MovementStatus
	4,  // 3: pb.MatchInfo.MatchStatus:type_name -> pb.MatchStatus
	4,  // 4: pb.PlayerMoveResponse.MatchStatus:type_name -> pb.MatchStatus
	4,  // 5: pb.MatchStatusResponse.MatchStatus:type_name -> pb.MatchStatus
	4,  // 6: pb.StopMatchResponse.MatchStatus:type_name -> pb.MatchStatus
	5,  // 7: pb.MathListResponse.MatchList:type_name -> pb.MatchInfo
	5,  // 8: pb.MatchMovementListResponse.MatchInfo:type_name -> pb.MatchInfo
	3,  // 9: pb.MatchMovementListResponse.MovementList:type_name -> pb.MovementInfo
	6,  // 10: pb.GameApi.JoinToLobby:input_type -> pb.JoinToLobbyRequest
	12, // 11: pb.GameApi.StopMatch:input_type -> pb.StopMatchRequest
	8,  // 12: pb.GameApi.PlayerMove:input_type -> pb.PlayerMoveRequest
	10, // 13: pb.GameApi.GetMatchStatus:input_type -> pb.MatchStatusRequest
	16, // 14: pb.GameApi.GetMatchMovementList:input_type -> pb.MatchMovementListRequest
	14, // 15: pb.GameApi.GetMatchList:input_type -> pb.MathListRequest
	7,  // 16: pb.GameApi.JoinToLobby:output_type -> pb.JoinToLobbyResponse
	13, // 17: pb.GameApi.StopMatch:output_type -> pb.StopMatchResponse
	9,  // 18: pb.GameApi.PlayerMove:output_type -> pb.PlayerMoveResponse
	11, // 19: pb.GameApi.GetMatchStatus:output_type -> pb.MatchStatusResponse
	17, // 20: pb.GameApi.GetMatchMovementList:output_type -> pb.MatchMovementListResponse
	15, // 21: pb.GameApi.GetMatchList:output_type -> pb.MathListResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovementInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinToLobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinToLobbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopMatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MathListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MathListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchMovementListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchMovementListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_rawDesc = nil
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
