// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.27.3
// source: server.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReasons int32

const (
	ErrorReasons_ACCESS_TOKEN_NOT_FOUND ErrorReasons = 0
	ErrorReasons_ACCESS_TOKEN_EXPIRED   ErrorReasons = 1
	ErrorReasons_SIGNATURE_FLOW_FAILED  ErrorReasons = 2
)

// Enum value maps for ErrorReasons.
var (
	ErrorReasons_name = map[int32]string{
		0: "ACCESS_TOKEN_NOT_FOUND",
		1: "ACCESS_TOKEN_EXPIRED",
		2: "SIGNATURE_FLOW_FAILED",
	}
	ErrorReasons_value = map[string]int32{
		"ACCESS_TOKEN_NOT_FOUND": 0,
		"ACCESS_TOKEN_EXPIRED":   1,
		"SIGNATURE_FLOW_FAILED":  2,
	}
)

func (x ErrorReasons) Enum() *ErrorReasons {
	p := new(ErrorReasons)
	*p = x
	return p
}

func (x ErrorReasons) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReasons) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (ErrorReasons) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x ErrorReasons) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReasons.Descriptor instead.
func (ErrorReasons) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type MatchProgressStatus int32

const (
	MatchProgressStatus_MATCH_STILL_IN_PROGRESS MatchProgressStatus = 0
	MatchProgressStatus_MATCH_ALREADY_ENDED     MatchProgressStatus = 1
)

// Enum value maps for MatchProgressStatus.
var (
	MatchProgressStatus_name = map[int32]string{
		0: "MATCH_STILL_IN_PROGRESS",
		1: "MATCH_ALREADY_ENDED",
	}
	MatchProgressStatus_value = map[string]int32{
		"MATCH_STILL_IN_PROGRESS": 0,
		"MATCH_ALREADY_ENDED":     1,
	}
)

func (x MatchProgressStatus) Enum() *MatchProgressStatus {
	p := new(MatchProgressStatus)
	*p = x
	return p
}

func (x MatchProgressStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchProgressStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[1].Descriptor()
}

func (MatchProgressStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[1]
}

func (x MatchProgressStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchProgressStatus.Descriptor instead.
func (MatchProgressStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

type CurrentMovementStatus int32

const (
	CurrentMovementStatus_AWAIT_FOR_0_MOVE CurrentMovementStatus = 0
	CurrentMovementStatus_AWAIT_FOR_X_MOVE CurrentMovementStatus = 1
)

// Enum value maps for CurrentMovementStatus.
var (
	CurrentMovementStatus_name = map[int32]string{
		0: "AWAIT_FOR_0_MOVE",
		1: "AWAIT_FOR_X_MOVE",
	}
	CurrentMovementStatus_value = map[string]int32{
		"AWAIT_FOR_0_MOVE": 0,
		"AWAIT_FOR_X_MOVE": 1,
	}
)

func (x CurrentMovementStatus) Enum() *CurrentMovementStatus {
	p := new(CurrentMovementStatus)
	*p = x
	return p
}

func (x CurrentMovementStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CurrentMovementStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[2].Descriptor()
}

func (CurrentMovementStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[2]
}

func (x CurrentMovementStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CurrentMovementStatus.Descriptor instead.
func (CurrentMovementStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

type NextMovementStatus int32

const (
	NextMovementStatus_NEXT_MOVE_O NextMovementStatus = 0
	NextMovementStatus_NEXT_MOVE_X NextMovementStatus = 1
)

// Enum value maps for NextMovementStatus.
var (
	NextMovementStatus_name = map[int32]string{
		0: "NEXT_MOVE_O",
		1: "NEXT_MOVE_X",
	}
	NextMovementStatus_value = map[string]int32{
		"NEXT_MOVE_O": 0,
		"NEXT_MOVE_X": 1,
	}
)

func (x NextMovementStatus) Enum() *NextMovementStatus {
	p := new(NextMovementStatus)
	*p = x
	return p
}

func (x NextMovementStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NextMovementStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[3].Descriptor()
}

func (NextMovementStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[3]
}

func (x NextMovementStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NextMovementStatus.Descriptor instead.
func (NextMovementStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

type MatchStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProgressStatus MatchProgressStatus   `protobuf:"varint,1,opt,name=ProgressStatus,proto3,enum=tiktaktoe.MatchProgressStatus" json:"ProgressStatus,omitempty"`
	MovementStatus CurrentMovementStatus `protobuf:"varint,2,opt,name=MovementStatus,proto3,enum=tiktaktoe.CurrentMovementStatus" json:"MovementStatus,omitempty"`
	NextMove       NextMovementStatus    `protobuf:"varint,3,opt,name=NextMove,proto3,enum=tiktaktoe.NextMovementStatus" json:"NextMove,omitempty"`
}

func (x *MatchStatus) Reset() {
	*x = MatchStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatus) ProtoMessage() {}

func (x *MatchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatus.ProtoReflect.Descriptor instead.
func (*MatchStatus) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *MatchStatus) GetProgressStatus() MatchProgressStatus {
	if x != nil {
		return x.ProgressStatus
	}
	return MatchProgressStatus_MATCH_STILL_IN_PROGRESS
}

func (x *MatchStatus) GetMovementStatus() CurrentMovementStatus {
	if x != nil {
		return x.MovementStatus
	}
	return CurrentMovementStatus_AWAIT_FOR_0_MOVE
}

func (x *MatchStatus) GetNextMove() NextMovementStatus {
	if x != nil {
		return x.NextMove
	}
	return NextMovementStatus_NEXT_MOVE_O
}

type MatchInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID   string       `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
	MatchStatus *MatchStatus `protobuf:"bytes,2,opt,name=MatchStatus,proto3" json:"MatchStatus,omitempty"`
}

func (x *MatchInfo) Reset() {
	*x = MatchInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfo) ProtoMessage() {}

func (x *MatchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfo.ProtoReflect.Descriptor instead.
func (*MatchInfo) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *MatchInfo) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

func (x *MatchInfo) GetMatchStatus() *MatchStatus {
	if x != nil {
		return x.MatchStatus
	}
	return nil
}

type StartMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleFieldSize uint32 `protobuf:"varint,1,opt,name=BattleFieldSize,proto3" json:"BattleFieldSize,omitempty"`
}

func (x *StartMatchRequest) Reset() {
	*x = StartMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchRequest) ProtoMessage() {}

func (x *StartMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchRequest.ProtoReflect.Descriptor instead.
func (*StartMatchRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *StartMatchRequest) GetBattleFieldSize() uint32 {
	if x != nil {
		return x.BattleFieldSize
	}
	return 0
}

type StartMatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID  string `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
	SignedData []byte `protobuf:"bytes,2,opt,name=SignedData,proto3" json:"SignedData,omitempty"`
}

func (x *StartMatchResponse) Reset() {
	*x = StartMatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchResponse) ProtoMessage() {}

func (x *StartMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchResponse.ProtoReflect.Descriptor instead.
func (*StartMatchResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *StartMatchResponse) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

func (x *StartMatchResponse) GetSignedData() []byte {
	if x != nil {
		return x.SignedData
	}
	return nil
}

type MakeMoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID string `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
}

func (x *MakeMoveRequest) Reset() {
	*x = MakeMoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRequest) ProtoMessage() {}

func (x *MakeMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *MakeMoveRequest) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

type MakeMoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID   string       `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
	MatchStatus *MatchStatus `protobuf:"bytes,2,opt,name=MatchStatus,proto3" json:"MatchStatus,omitempty"`
}

func (x *MakeMoveResponse) Reset() {
	*x = MakeMoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveResponse) ProtoMessage() {}

func (x *MakeMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveResponse.ProtoReflect.Descriptor instead.
func (*MakeMoveResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *MakeMoveResponse) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

func (x *MakeMoveResponse) GetMatchStatus() *MatchStatus {
	if x != nil {
		return x.MatchStatus
	}
	return nil
}

type MatchStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID string `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
}

func (x *MatchStatusRequest) Reset() {
	*x = MatchStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatusRequest) ProtoMessage() {}

func (x *MatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatusRequest.ProtoReflect.Descriptor instead.
func (*MatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *MatchStatusRequest) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

type MatchStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchUUID   string       `protobuf:"bytes,1,opt,name=MatchUUID,proto3" json:"MatchUUID,omitempty"`
	MatchStatus *MatchStatus `protobuf:"bytes,2,opt,name=MatchStatus,proto3" json:"MatchStatus,omitempty"`
}

func (x *MatchStatusResponse) Reset() {
	*x = MatchStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatusResponse) ProtoMessage() {}

func (x *MatchStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatusResponse.ProtoReflect.Descriptor instead.
func (*MatchStatusResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *MatchStatusResponse) GetMatchUUID() string {
	if x != nil {
		return x.MatchUUID
	}
	return ""
}

func (x *MatchStatusResponse) GetMatchStatus() *MatchStatus {
	if x != nil {
		return x.MatchStatus
	}
	return nil
}

type StopMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameUUID string `protobuf:"bytes,1,opt,name=GameUUID,proto3" json:"GameUUID,omitempty"`
}

func (x *StopMatchRequest) Reset() {
	*x = StopMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMatchRequest) ProtoMessage() {}

func (x *StopMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMatchRequest.ProtoReflect.Descriptor instead.
func (*StopMatchRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *StopMatchRequest) GetGameUUID() string {
	if x != nil {
		return x.GameUUID
	}
	return ""
}

type StopMatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameUUID    string       `protobuf:"bytes,1,opt,name=GameUUID,proto3" json:"GameUUID,omitempty"`
	MatchStatus *MatchStatus `protobuf:"bytes,2,opt,name=MatchStatus,proto3" json:"MatchStatus,omitempty"`
}

func (x *StopMatchResponse) Reset() {
	*x = StopMatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMatchResponse) ProtoMessage() {}

func (x *StopMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMatchResponse.ProtoReflect.Descriptor instead.
func (*StopMatchResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *StopMatchResponse) GetGameUUID() string {
	if x != nil {
		return x.GameUUID
	}
	return ""
}

func (x *StopMatchResponse) GetMatchStatus() *MatchStatus {
	if x != nil {
		return x.MatchStatus
	}
	return nil
}

type MathListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MathListRequest) Reset() {
	*x = MathListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MathListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathListRequest) ProtoMessage() {}

func (x *MathListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathListRequest.ProtoReflect.Descriptor instead.
func (*MathListRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

type MathListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchList []*MatchInfo `protobuf:"bytes,1,rep,name=MatchList,proto3" json:"MatchList,omitempty"`
}

func (x *MathListResponse) Reset() {
	*x = MathListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MathListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathListResponse) ProtoMessage() {}

func (x *MathListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathListResponse.ProtoReflect.Descriptor instead.
func (*MathListResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *MathListResponse) GetMatchList() []*MatchInfo {
	if x != nil {
		return x.MatchList
	}
	return nil
}

var File_server_proto protoreflect.FileDescriptor

var file_server_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x22, 0xda, 0x01, 0x0a, 0x0b, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x46, 0x0a, 0x0e, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x48, 0x0a, 0x0e, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x74, 0x69, 0x6b, 0x74,
	0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x76,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x4d, 0x6f, 0x76,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x08, 0x4e,
	0x65, 0x78, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x6f,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x08, 0x4e, 0x65,
	0x78, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x22, 0x63, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49,
	0x44, 0x12, 0x38, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74,
	0x6f, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3d, 0x0a, 0x11, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x0f, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x52, 0x0a, 0x12, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1e,
	0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2f,
	0x0a, 0x0f, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x22,
	0x6a, 0x0a, 0x10, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49,
	0x44, 0x12, 0x38, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74,
	0x6f, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x32, 0x0a, 0x12, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x55, 0x49, 0x44, 0x22,
	0x6d, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x55, 0x55, 0x49, 0x44, 0x12, 0x38, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x69, 0x6b, 0x74,
	0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2e,
	0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x55, 0x49, 0x44, 0x22, 0x69,
	0x0a, 0x11, 0x53, 0x74, 0x6f, 0x70, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x55, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x55, 0x49, 0x44, 0x12,
	0x38, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65,
	0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x4d, 0x61, 0x74,
	0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x10,
	0x4d, 0x61, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x4c, 0x69, 0x73, 0x74, 0x2a, 0x5f, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x54,
	0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00,
	0x12, 0x18, 0x0a, 0x14, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e,
	0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x49,
	0x47, 0x4e, 0x41, 0x54, 0x55, 0x52, 0x45, 0x5f, 0x46, 0x4c, 0x4f, 0x57, 0x5f, 0x46, 0x41, 0x49,
	0x4c, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x4b, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17,
	0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x49, 0x4c, 0x4c, 0x5f, 0x49, 0x4e, 0x5f, 0x50,
	0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x41, 0x54,
	0x43, 0x48, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44,
	0x10, 0x01, 0x2a, 0x43, 0x0a, 0x15, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x76,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x10, 0x41,
	0x57, 0x41, 0x49, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x5f, 0x30, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x57, 0x41, 0x49, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x5f, 0x58,
	0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x01, 0x2a, 0x36, 0x0a, 0x12, 0x4e, 0x65, 0x78, 0x74, 0x4d,
	0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a,
	0x0b, 0x4e, 0x45, 0x58, 0x54, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4f, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x4e, 0x45, 0x58, 0x54, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x58, 0x10, 0x01, 0x32,
	0x85, 0x03, 0x0a, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x70, 0x69, 0x12, 0x4b, 0x0a, 0x0a, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1c, 0x2e, 0x74, 0x69, 0x6b, 0x74,
	0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b,
	0x74, 0x6f, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x70,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1c, 0x2e, 0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x08, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65,
	0x12, 0x1a, 0x2e, 0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x61, 0x6b,
	0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74,
	0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x2e, 0x74,
	0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x69,
	0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x74,
	0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x68, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x69, 0x6b, 0x74, 0x61,
	0x6b, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x6d, 0x61, 0x69, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData = file_server_proto_rawDesc
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_rawDescData)
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_server_proto_goTypes = []interface{}{
	(ErrorReasons)(0),           // 0: tiktaktoe.ErrorReasons
	(MatchProgressStatus)(0),    // 1: tiktaktoe.MatchProgressStatus
	(CurrentMovementStatus)(0),  // 2: tiktaktoe.CurrentMovementStatus
	(NextMovementStatus)(0),     // 3: tiktaktoe.NextMovementStatus
	(*MatchStatus)(nil),         // 4: tiktaktoe.MatchStatus
	(*MatchInfo)(nil),           // 5: tiktaktoe.MatchInfo
	(*StartMatchRequest)(nil),   // 6: tiktaktoe.StartMatchRequest
	(*StartMatchResponse)(nil),  // 7: tiktaktoe.StartMatchResponse
	(*MakeMoveRequest)(nil),     // 8: tiktaktoe.MakeMoveRequest
	(*MakeMoveResponse)(nil),    // 9: tiktaktoe.MakeMoveResponse
	(*MatchStatusRequest)(nil),  // 10: tiktaktoe.MatchStatusRequest
	(*MatchStatusResponse)(nil), // 11: tiktaktoe.MatchStatusResponse
	(*StopMatchRequest)(nil),    // 12: tiktaktoe.StopMatchRequest
	(*StopMatchResponse)(nil),   // 13: tiktaktoe.StopMatchResponse
	(*MathListRequest)(nil),     // 14: tiktaktoe.MathListRequest
	(*MathListResponse)(nil),    // 15: tiktaktoe.MathListResponse
}
var file_server_proto_depIdxs = []int32{
	1,  // 0: tiktaktoe.MatchStatus.ProgressStatus:type_name -> tiktaktoe.MatchProgressStatus
	2,  // 1: tiktaktoe.MatchStatus.MovementStatus:type_name -> tiktaktoe.CurrentMovementStatus
	3,  // 2: tiktaktoe.MatchStatus.NextMove:type_name -> tiktaktoe.NextMovementStatus
	4,  // 3: tiktaktoe.MatchInfo.MatchStatus:type_name -> tiktaktoe.MatchStatus
	4,  // 4: tiktaktoe.MakeMoveResponse.MatchStatus:type_name -> tiktaktoe.MatchStatus
	4,  // 5: tiktaktoe.MatchStatusResponse.MatchStatus:type_name -> tiktaktoe.MatchStatus
	4,  // 6: tiktaktoe.StopMatchResponse.MatchStatus:type_name -> tiktaktoe.MatchStatus
	5,  // 7: tiktaktoe.MathListResponse.MatchList:type_name -> tiktaktoe.MatchInfo
	6,  // 8: tiktaktoe.GameApi.StartMatch:input_type -> tiktaktoe.StartMatchRequest
	6,  // 9: tiktaktoe.GameApi.StopMatch:input_type -> tiktaktoe.StartMatchRequest
	8,  // 10: tiktaktoe.GameApi.MakeMove:input_type -> tiktaktoe.MakeMoveRequest
	10, // 11: tiktaktoe.GameApi.GetMathStatus:input_type -> tiktaktoe.MatchStatusRequest
	14, // 12: tiktaktoe.GameApi.GetMathList:input_type -> tiktaktoe.MathListRequest
	7,  // 13: tiktaktoe.GameApi.StartMatch:output_type -> tiktaktoe.StartMatchResponse
	7,  // 14: tiktaktoe.GameApi.StopMatch:output_type -> tiktaktoe.StartMatchResponse
	9,  // 15: tiktaktoe.GameApi.MakeMove:output_type -> tiktaktoe.MakeMoveResponse
	11, // 16: tiktaktoe.GameApi.GetMathStatus:output_type -> tiktaktoe.MatchStatusResponse
	15, // 17: tiktaktoe.GameApi.GetMathList:output_type -> tiktaktoe.MathListResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeMoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeMoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopMatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MathListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MathListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_rawDesc = nil
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
